### PR TITLE
Added JasonB

### PR DESCRIPTION
**Pull request by Craterbrain**
Check the formatting. I'm doing this on my phone.

### CODE REVIEW

**Comment by cyckl** [comment]
currently reworking the way that users are displayed and accessed. i'll update the issue once everything is setup properly and we can continue with adding you

**Comment by Craterbrain** [comment]
Ok, cool

**Comment by cyckl** [comment]
rework complete! you can go ahead and edit your patch and i can merge it in

**Comment by cyckl** [comment]
eh i just did it manually lol

**Pull request closed without merging**
